### ISSUE TITLE
Update README.md

### ISSUE THREAD

**Issue by rossoskull** [cerebro-iiitv/cerebro-web-2020#3]

**Comment by rossoskull** [comment]
Refer https://github.com/cerebro-iiitv/cerebro-web-2019/blob/master/README.md

<blockquote><img src="https://avatars1.githubusercontent.com/u/36279124?s=400&v=4" width="48" align="right"><div><img src="https://github.githubassets.com/favicon.ico" height="14"> GitHub</div><div><strong><a href="https://github.com/cerebro-iiitv/cerebro-web-2019">cerebro-iiitv/cerebro-web-2019</a></strong></div><div>Cerebro's Landing Website for 2019. Contribute to cerebro-iiitv/cerebro-web-2019 development by creating an account on GitHub.</div></blockquote>

**Comment by thepushkarp** [comment]
@prathmeshkhandelwal1 any updates on this?

**Comment by thepushkarp** [comment]
Closed via #48
