### ISSUE TITLE
Bugs in mobile view

### ISSUE THREAD

**Issue by pAditya198** [cerebro-iiitv/cerebro-web-2020#32]
Fix mobile view for about and past glimpse component

![Screenshot_2020-02-20-15-14-36-448_com android chrome](https://user-images.githubusercontent.com/42460356/74921512-e3aac780-53f3-11ea-85fe-fd55b1962548.jpg)
![Screenshot_2020-02-20-15-14-44-426_com android chrome](https://user-images.githubusercontent.com/42460356/74921535-ec030280-53f3-11ea-9ac9-fa1fc62df506.jpg)
![Screenshot_2020-02-20-15-14-49-428_com android chrome](https://user-images.githubusercontent.com/42460356/74921557-f1604d00-53f3-11ea-9536-1133529492fc.jpg)

**Comment by anujpuri72** [comment]
Since it is fixed ,issue can be closed now
