### ISSUE TITLE
Add last year pics in Past Year Glimpses

### ISSUE THREAD

**Issue by thepushkarp** [cerebro-iiitv/cerebro-web-2020#52]
Update the Past Year Glimpses section at Homepage with last year pics.

@yashshah2820 will be sharing the links to the pics here.

**Comment by theyashshahs** [comment]
These are the links for the images 
https://user-images.githubusercontent.com/42682370/75119495-4d073080-56a9-11ea-8369-8a28f159e2ac.JPG
https://user-images.githubusercontent.com/42682370/75119512-7f189280-56a9-11ea-9aad-0dd0098d0892.JPG
https://user-images.githubusercontent.com/42682370/75119519-8fc90880-56a9-11ea-8cf8-13c9b2682782.JPG
https://user-images.githubusercontent.com/42682370/75119527-a1aaab80-56a9-11ea-8450-43175d57cffe.JPG
https://user-images.githubusercontent.com/42682370/75119569-10880480-56aa-11ea-9d3c-3c8a51e5ab4d.JPG
https://user-images.githubusercontent.com/42682370/75119594-5218af80-56aa-11ea-97b4-bf79540f1f11.JPG
https://user-images.githubusercontent.com/42682370/75119615-812f2100-56aa-11ea-9049-de00e2109a48.JPG
https://user-images.githubusercontent.com/42682370/75119693-2f3acb00-56ab-11ea-9341-3bc43ec95856.JPG
https://user-images.githubusercontent.com/42682370/75119695-3feb4100-56ab-11ea-99c5-9652ca06ee0a.JPG
https://user-images.githubusercontent.com/42682370/75119707-5db8a600-56ab-11ea-8dda-d445b0a5b602.JPG
https://user-images.githubusercontent.com/42682370/75119744-b425e480-56ab-11ea-853d-1e254a034db3.JPG
https://user-images.githubusercontent.com/42682370/75119817-5d6cda80-56ac-11ea-9670-3a3968b4ec11.JPG

<blockquote></blockquote>
<blockquote></blockquote>
<blockquote></blockquote>
<blockquote></blockquote>
<blockquote></blockquote>
<blockquote></blockquote>
<blockquote></blockquote>
<blockquote></blockquote>
<blockquote></blockquote>
<blockquote></blockquote>
<blockquote></blockquote>
<blockquote></blockquote>

**Comment by eshaan007** [comment]
I would like to take up this issue.

**Comment by eshaan007** [comment]
![pastYearGlimpses](https://user-images.githubusercontent.com/42370985/75249772-e8f58100-57fc-11ea-8439-7b5a0851c8f4.PNG)

This issue has been resolved.
Task completed...

**Comment by thepushkarp** [comment]
Closed via #53
