### ISSUE TITLE
add new images in past glimpse section

### ISSUE THREAD

**Issue by theyashshahs** [cerebro-iiitv/cerebro-web-2020#61]
https://user-images.githubusercontent.com/42682370/75565883-ccfc1480-5a74-11ea-8b46-7a55b7161d98.jpg

https://user-images.githubusercontent.com/42682370/75566009-06cd1b00-5a75-11ea-9a3c-7abc661d45ad.jpg

https://user-images.githubusercontent.com/42682370/75566128-31b76f00-5a75-11ea-8878-41cf30971564.jpg

https://user-images.githubusercontent.com/42682370/75566374-8fe45200-5a75-11ea-9406-d88cb018c8c5.jpg

https://user-images.githubusercontent.com/42682370/75566610-fe291480-5a75-11ea-9eda-d3e4784adf69.JPG

https://user-images.githubusercontent.com/42682370/75566898-8e675980-5a76-11ea-8be8-4d42bcc505a9.JPG

**Comment by thepushkarp** [comment]
@eshaan007 you up on this?

**Comment by theyashshahs** [comment]
this issue has been dealt with
